export const placeholderData = {
  "react": [
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "8-WDpZDXw9oAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "React Developer - Contract to hire",
        "job_apply_link": "https://www.upwork.com/en-gb/freelance-jobs/apply/React-Developer_~017098b14e33c2bd6f/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6815,
        "job_description": "In the attachment PDF all the detailse exists.\n\nIn order to be sure of the person who will do the project, we will give a page that we think is of medium difficulty as an assignment. If we are satisfied with the candidate, if he can implement that page well, we will work together for the whole project.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691435191,
        "job_posted_at_datetime_utc": "2023-08-07T19:06:31.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=8-WDpZDXw9oAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": [
            "React",
            "CSS",
            "JavaScript",
            "HTML",
            "Web Application",
            "Web Development"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Responsibilities": [
                "In order to be sure of the person who will do the project, we will give a page that we think is of medium difficulty as an assignment"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "The Intersect Group",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXUa27UqNXetjZZZUrU0eVWWs_4NQs-l9dwRhZ&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "LinkedIn",
        "job_id": "ZqzpbGJpoCsAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "React Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/react-developer-at-the-intersect-group-3683661011",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5594,
        "job_description": "Job Title: React Developer\n\nType: Direct- Hire\n\nLocation: 100% Remote\n\nJob Responsibilities:\n• Codes front-end elements using HTML, CSS and Javascript, React\n• Codes WordPress plugins and updates themes for feature and security improvements.\n• Builds reusable code and libraries for use in other applications built in Wordpress or CodeIgniter.\n• Optimizes the application for maximum speed and scalability\n• Implements security and data protection\n• Other duties as assigned\n\nRequirements:\n• Bachelor-level degree or equivalent experience required.\n• (5) years' experience in corporate web site development.\n• Strong preference of server-side programming languages knowledge - PHP, Node.js, etc.\n• Proficient understanding of code versioning tools, such as Git.\n• Understanding of front-end technologies and platforms, such as JavaScript, JQuery, VueJS, Foundation, Bootstrap, React, HTML5, and CSS3.\n• Good understanding of server-side CSS preprocessors, such as LESS and SASS.\n• Understanding accessibility and security compliance.\n• User authentication and authorization between multiple systems, servers, and environments.\n• Understanding differences between multiple delivery platforms such as mobile vs desktop, and optimizing output to match the specific platform.\n• Implementing automated testing platforms and unit tests.\n• Proficient understanding of OWASP security principles.\n• Working knowledge of WordPress development.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691413516,
        "job_posted_at_datetime_utc": "2023-08-07T13:05:16.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=ZqzpbGJpoCsAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-09-06T13:05:15.000Z",
        "job_offer_expiration_timestamp": 1694005515,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 60,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 100000,
        "job_max_salary": 110000,
        "job_salary_currency": "USD",
        "job_salary_period": "YEAR",
        "job_highlights": {
            "Qualifications": [
                "Bachelor-level degree or equivalent experience required",
                "(5) years' experience in corporate web site development",
                "Strong preference of server-side programming languages knowledge - PHP, Node.js, etc",
                "Proficient understanding of code versioning tools, such as Git",
                "Understanding of front-end technologies and platforms, such as JavaScript, JQuery, VueJS, Foundation, Bootstrap, React, HTML5, and CSS3",
                "Good understanding of server-side CSS preprocessors, such as LESS and SASS",
                "Understanding accessibility and security compliance",
                "User authentication and authorization between multiple systems, servers, and environments",
                "Understanding differences between multiple delivery platforms such as mobile vs desktop, and optimizing output to match the specific platform",
                "Implementing automated testing platforms and unit tests",
                "Proficient understanding of OWASP security principles",
                "Working knowledge of WordPress development"
            ],
            "Responsibilities": [
                "Codes front-end elements using HTML, CSS and Javascript, React",
                "Codes WordPress plugins and updates themes for feature and security improvements",
                "Builds reusable code and libraries for use in other applications built in Wordpress or CodeIgniter",
                "Optimizes the application for maximum speed and scalability",
                "Implements security and data protection",
                "Other duties as assigned"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3"
    },
    {
        "employer_name": "Bass Pro Shops, Bass Pro Shops",
        "employer_logo": "https://upload.wikimedia.org/wikipedia/en/5/5b/Bass_Pro_Shops_logo.png",
        "employer_website": "http://www.basspro.com",
        "employer_company_type": "Retail",
        "job_publisher": "Bass Pro Shops Jobs",
        "job_id": "pF4M_gBZl9kAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Frontend React Dev 3",
        "job_apply_link": "https://careers.basspro.com/us/en/job/R137768/Frontend-React-Dev-3",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.7999,
        "job_description": "Frontend React Developer will be a member of Digital Commerce team responsible for developing and supporting eCommerce capabilities on multiple brand websites. As part of a dynamic team with growing demand, this role will be responsible for requirement gathering, developing & testing website related enhancements, as well as troubleshooting and remediating issues within the application. This includes support for end-to-end application testing, understanding of integrations to upstream/downstream systems, and adhering to code management activities within an agile framework. This role will work with on/offshore dev team members in supporting and delivering solutions.\n\nRequired Skills & Experience\n• 3+ years hands-on experience in developing and minimum 2 years’ experience with React or other JS based technologies\n• BS degree in Computer Science or related field\n• Solid understanding of web technologies, including HTML, CSS3, and JavaScript\n• Ability to integrate 3rd party APIs and a strong understanding of REST and other API patterns\n• Experience working on NodeJS, ReactJS, Angular, Bootstrap, Typescript\n• Experience with state management like Redux, React-Context, Recoil or similar library\n• Knowledge on JavaScript ES6 features such as classes, arrow functions, string templates, rest/spread operators, promises, async/await\n• Familiar with building responsive layouts using CSS and its compiler workflows (e.g. LESS, SASS/SCSS, styled components).\n• Strong understanding of CS fundamentals, Object Oriented Design and Data Structures\n• Strong troubleshooting and problem-solving skills, strong interpersonal, verbal, and written communication skills, strong relationship builder in cross-functional teams.\n• Experience building, optimizing, and maintaining websites with high traffic and performance demands\n• Familiarity using SVN/GIT/Bitbucket for source code management and Atlassian tools Jira and Confluence.\n\nPreferred Skills & Experience\n• Experience working in a Retail eCommerce environment\n• Familiarity with front-end build tools, such as Webpack, Grunt and Gulp.js\n• Good understanding of asynchronous, closure, event-driven programming\n• Understanding of web accessibility principles, patterns, and testing\n• Worked on design systems building highly composable, reusable components\n• Experience translating design mockups and prototypes into working application designs.\n• Have a great attitude and fit in a fun team and collaborative environment\n• Excited about technology and strong interest in learning latest technologies\n\nEqual Opportunity Employer\n\nBass Pro Shops is an equal opportunity employer. Hiring decisions are administered without regard to race, color, creed, religion, sex, pregnancy, sexual orientation, gender identity, age, national origin, ancestry, citizenship status, disability, veteran status, genetic information, or any other basis protected by applicable federal, state or local law.\n\nReasonable Accommodations\n\nQualified individuals with known disabilities may be entitled to reasonable accommodation under the Americans with Disabilities Act and certain state or local laws.\n\nIf you need a reasonable accommodation for any part of the application process, please visit your nearest location or contact us at hrcompliance@basspro.com.\n\nFull Time Benefits Summary:\nEnjoy discounts on retail merchandise, our restaurants, world-class resorts and conservation attractions!\n• Medical\n• Dental\n• Vision\n• Health Savings Account\n• Flexible Spending Account\n• Voluntary benefits\n• 401k Retirement Savings\n• Paid holidays\n• Paid vacation\n• Paid sick time\n• Bass Pro Cares Fund\n• And more!\n\nBass Pro Shops is an equal opportunity employer. Hiring decisions are administered without regard to race, color, creed, religion, sex, pregnancy, sexual orientation, gender identity, age, national origin, ancestry, citizenship status, disability, veteran status, genetic information, or any other basis protected by applicable federal, state or local law.\n\nReasonable Accommodations\n\nQualified individuals with known disabilities may be entitled to reasonable accommodation under the Americans with Disabilities Act and certain state or local laws.\nIf you need a reasonable accommodation for any part of the application process, please visit your nearest location or contact us at hrcompliance@basspro.com.\nBass Pro Shops",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1646179200,
        "job_posted_at_datetime_utc": "2022-03-02T00:00:00.000Z",
        "job_city": "Springfield",
        "job_state": "MO",
        "job_country": "US",
        "job_latitude": 37.208958,
        "job_longitude": -93.2923,
        "job_benefits": [
            "paid_time_off",
            "retirement_savings",
            "health_insurance"
        ],
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=pF4M_gBZl9kAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 36,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Dev Team",
            "React",
            "CSS3",
            "Gulp.js",
            "Web Technologies",
            "javascript es6",
            "Angular",
            "svn",
            "Redux",
            "Object Oriented Design",
            "HTML",
            "API",
            "Jira",
            "Webpack",
            "cs fundamentals",
            "SCSS",
            "Web Accessibility",
            "Grunt",
            "Confluence",
            "Sass",
            "TypeScript",
            "Atlassian",
            "Git",
            "Compiler",
            "Bootstrap",
            "Code Management",
            "Agile Framework",
            "Templates",
            "Data Structures",
            "Bitbucket",
            "Team Lead - Algorithm Development & Performance Optimization",
            "Senior Engineer - Kafka",
            "Spark",
            "Hadoop",
            "React",
            "NoSQL",
            "Lead Engineer - React & React Native & javascript",
            "Open Source Java Developer - Hazelcast & Cassandra",
            "Interactive Developer - HTML & CSS & Javascript",
            "Back-End Java Engineer - Spring & Hibernate & Restful APIs",
            "Senior UI Developer - Javascript & Html & Css & Silverlight & Adobe Flex & Flash",
            "Magento Developer - Magento & PHP & Relational Databases - MySQL",
            "Freelancer Web Design & Development & Search Engine Optimization",
            "Front End Developer - React.js & Backbone.js & Javascript & Node.Js"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": true,
            "degree_preferred": true,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "3+ years hands-on experience in developing and minimum 2 years’ experience with React or other JS based technologies",
                "BS degree in Computer Science or related field",
                "Solid understanding of web technologies, including HTML, CSS3, and JavaScript",
                "Ability to integrate 3rd party APIs and a strong understanding of REST and other API patterns",
                "Experience working on NodeJS, ReactJS, Angular, Bootstrap, Typescript",
                "Experience with state management like Redux, React-Context, Recoil or similar library",
                "Knowledge on JavaScript ES6 features such as classes, arrow functions, string templates, rest/spread operators, promises, async/await",
                "Familiar with building responsive layouts using CSS and its compiler workflows (e.g. LESS, SASS/SCSS, styled components)",
                "Strong understanding of CS fundamentals, Object Oriented Design and Data Structures",
                "Strong troubleshooting and problem-solving skills, strong interpersonal, verbal, and written communication skills, strong relationship builder in cross-functional teams",
                "Experience building, optimizing, and maintaining websites with high traffic and performance demands",
                "Familiarity using SVN/GIT/Bitbucket for source code management and Atlassian tools Jira and Confluence"
            ],
            "Responsibilities": [
                "Frontend React Developer will be a member of Digital Commerce team responsible for developing and supporting eCommerce capabilities on multiple brand websites",
                "As part of a dynamic team with growing demand, this role will be responsible for requirement gathering, developing & testing website related enhancements, as well as troubleshooting and remediating issues within the application",
                "This includes support for end-to-end application testing, understanding of integrations to upstream/downstream systems, and adhering to code management activities within an agile framework",
                "This role will work with on/offshore dev team members in supporting and delivering solutions"
            ],
            "Benefits": [
                "Vision",
                "Health Savings Account",
                "Flexible Spending Account",
                "Voluntary benefits",
                "401k Retirement Savings",
                "Paid holidays",
                "Paid vacation",
                "Paid sick time",
                "Bass Pro Cares Fund"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_occupational_categories": [
            "Base Camp HQ"
        ],
        "job_naics_code": "44832",
        "job_naics_name": "Luggage and Leather Goods Stores"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "fMHw0-ui5cEAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Frontend React Developer Needed - Contract to hire",
        "job_apply_link": "https://www.upwork.com/en-gb/freelance-jobs/apply/Frontend-React-Developer-Needed_~01fdbfbe53f10bf6c3/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.7724,
        "job_description": "Hello. Right now we are looking for an Intermediate React Developer to provide us with a reskin of our platform. Be able to take Figma assets and develop our site to look identical to our designs. We also would like to reorganize our CSS files to make sure our styling is efficient. Knowing TailWind CSS would be a bonus as we want to make sure reusable components get used throughout our platform. This could lead to a permanent position.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691173478,
        "job_posted_at_datetime_utc": "2023-08-04T18:24:38.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=fMHw0-ui5cEAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Tailwind CSS",
            "Web Application",
            "React",
            "CSS",
            "HTML5",
            "JavaScript"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 15,
        "job_max_salary": 30,
        "job_salary_currency": "USD",
        "job_salary_period": "HOUR",
        "job_highlights": {
            "Responsibilities": [
                "Be able to take Figma assets and develop our site to look identical to our designs",
                "We also would like to reorganize our CSS files to make sure our styling is efficient"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "Mindpal",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKdbXDdBF2_8ZRV4qszl-0nJx1pneJLHoI9D9d&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "LinkedIn",
        "job_id": "1LMxW8i6w1AAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "React Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/react-developer-at-mindpal-3684273999",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5631,
        "job_description": "We are looking for React Developers with experience ranging from junior to senior level.\n\nJob Description\n• Creating and developing web applications using React and other front-end tools\n• Working with designers to translate graphical designs into visually appealing and intuitive user interfaces\n• Ensuring application performance and scalability through code optimization and problem-solving related to performance\n• Collaborating with the back-end team to integrate the front-end application with systems and databases\n• Testing and debugging applications to ensure reliability\n• Keeping up with the latest trends and tools in front-end development and improving skills to continuously enhance the quality of created applications\n• Collaborating with the project team and management to understand business requirements and adjust work to company goals\n\nRequirements\n• Minimum 2 years of experience working with React\n• Very good programming skills in JavaScript and TypeScript\n• Knowledge of software architecture, design patterns, and software development according to best practices\n• Communicative knowledge of English language\n• Additional advantage will be knowledge of other technologies\n\nWe Offer\n• B2B contract type\n• Full-time employment\n• Remote and flexible working hours\n\nRequirements\n\nResponsibilities",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1691138948,
        "job_posted_at_datetime_utc": "2023-08-04T08:49:08.000Z",
        "job_city": "Spokane",
        "job_state": "MO",
        "job_country": "US",
        "job_latitude": 36.8626,
        "job_longitude": -93.30616,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=1LMxW8i6w1AAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-09-03T08:49:08.000Z",
        "job_offer_expiration_timestamp": 1693730948,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Minimum 2 years of experience working with React",
                "Very good programming skills in JavaScript and TypeScript",
                "Knowledge of software architecture, design patterns, and software development according to best practices",
                "Communicative knowledge of English language",
                "Additional advantage will be knowledge of other technologies"
            ],
            "Responsibilities": [
                "Creating and developing web applications using React and other front-end tools",
                "Working with designers to translate graphical designs into visually appealing and intuitive user interfaces",
                "Ensuring application performance and scalability through code optimization and problem-solving related to performance",
                "Collaborating with the back-end team to integrate the front-end application with systems and databases",
                "Testing and debugging applications to ensure reliability",
                "Keeping up with the latest trends and tools in front-end development and improving skills to continuously enhance the quality of created applications",
                "Collaborating with the project team and management to understand business requirements and adjust work to company goals"
            ],
            "Benefits": [
                "B2B contract type",
                "Full-time employment",
                "Remote and flexible working hours"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "0uaY8z_zYIYAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "React Developer Needed",
        "job_apply_link": "https://www.upwork.com/freelance-jobs/apply/React-Developer-Needed_~01468be5b24eb44308/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6815,
        "job_description": "I'm looking for a developer to help me write enhancements for the admin console of my web application. There is already a functional site that has lots of functionality, this will be mainly working on enhancements. You should feel comfortable with proper software development practices (eg: github, staging environments) and AWS.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691196741,
        "job_posted_at_datetime_utc": "2023-08-05T00:52:21.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=0uaY8z_zYIYAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": [
            "React",
            "JavaScript",
            "Web Development"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 15,
        "job_max_salary": 40,
        "job_salary_currency": "USD",
        "job_salary_period": "HOUR",
        "job_highlights": {
            "Responsibilities": [
                "There is already a functional site that has lots of functionality, this will be mainly working on enhancements"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "OyYtO8FX-BYAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Need React developer to implement a few small changes",
        "job_apply_link": "https://www.upwork.com/freelance-jobs/apply/Need-React-developer-implement-few-small-changes_~01cd25c7bae5adbac6/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.7825,
        "job_description": "Looking for a strong ReactJS developer to make a few small design changes to our dashboard.\n\nSidebar changes (sidebar_current_design vs sidebar_redesign images attached)\n\nHeader changes (header_current_design vs header_redesign)\n\nThis is a pilot project. If we work well, we may collaborate on other design/development projects.\n\nOur application is Ruby on Rails + ReactJS",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691143795,
        "job_posted_at_datetime_utc": "2023-08-04T10:09:55.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=OyYtO8FX-BYAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": [
            "React",
            "Ruby on Rails"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "Insight Global",
        "employer_logo": "https://images.squarespace-cdn.com/content/5f7f984c3ca20d1d55b276f7/1619793549819-L54X3W9Z5RD277UPNH9S/IGLogoPublic.png?content-type=image%2Fpng",
        "employer_website": "http://www.insightglobal.com",
        "employer_company_type": "Staffing",
        "job_publisher": "Insight Global",
        "job_id": "5v4lTDKSorEAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Sr React Developer",
        "job_apply_link": "https://jobs.insightglobal.com/find_a_job/arkansas/bentonville/sr-react-developer/job-284984/",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.7773,
        "job_description": "One of our largest national retail clients is looking for a Sr. React Developer to join their growing Data Venture organization. The candidate will be partnering closely with the UX and design team to build out a new frontend application. You will be owning your own CICD pipeline, building containers and artifacts, running with the repositories, owning jenkin/looper jobs. For the code coverage you will be doing full fledge development along with working on the NFR aspects. 90% of the time will be working on Front end and 10% will be on the backend.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1683072000,
        "job_posted_at_datetime_utc": "2023-05-03T00:00:00.000Z",
        "job_city": "Bentonville",
        "job_state": "AR",
        "job_country": "US",
        "job_latitude": 36.372356,
        "job_longitude": -94.21021,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=5v4lTDKSorEAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-10-02T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1696204800,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Java/J2EE Experience working on external customer facing web applications"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Responsibilities": [
                "The candidate will be partnering closely with the UX and design team to build out a new frontend application",
                "You will be owning your own CICD pipeline, building containers and artifacts, running with the repositories, owning jenkin/looper jobs",
                "For the code coverage you will be doing full fledge development along with working on the NFR aspects",
                "90% of the time will be working on Front end and 10% will be on the backend"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "561311",
        "job_naics_name": "Employment Placement Agencies"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "Pwaz0QWsc44AAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Looking for a Nest + React developer (CRM project)",
        "job_apply_link": "https://www.upwork.com/freelance-jobs/apply/Looking-for-Nest-React-developer-CRM-project_~01a3c72532a284ff45/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6815,
        "job_description": "I'm looking for a Nest + React developer, matching the following requirements, for a CRM project:\n\n- Strong proficiency in Next.js and React development, with previous experience in building complex web applications.\n\n- Experience in Node.js and NestJS\n\n- Experience with TypeScript\n\n- Knowledge of databases: Amazon DynamoDB, (MongoDB) and Redis\n\n- A team player who enjoys working in a collaborative environment (Git, Agile, Scrum)\n\n- Experience with CRM APIs (Hubspot, Quickbooks)\n\n- Familiarity with Apollo for GraphQL data fetching and state management will be a plus",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691478542,
        "job_posted_at_datetime_utc": "2023-08-08T07:09:02.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=Pwaz0QWsc44AAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Node.js",
            "React",
            "Amazon DynamoDB",
            "NestJS",
            "HubSpot",
            "Quickbooks"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 20,
        "job_max_salary": 30,
        "job_salary_currency": "USD",
        "job_salary_period": "HOUR",
        "job_highlights": {
            "Qualifications": [
                "Strong proficiency in Next.js and React development, with previous experience in building complex web applications",
                "Experience in Node.js and NestJS",
                "Experience with TypeScript",
                "Knowledge of databases: Amazon DynamoDB, (MongoDB) and Redis",
                "A team player who enjoys working in a collaborative environment (Git, Agile, Scrum)",
                "Experience with CRM APIs (Hubspot, Quickbooks)"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "1MpkfgbWcNMAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "React Developer - Contract to Hire",
        "job_apply_link": "https://www.upwork.com/freelance-jobs/apply/React-Developer_~01b54eff2d0267655c/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6815,
        "job_description": "We are seeking a skilled React Developer to build a customer portal from scratch using Tailwind and Next.js. In this role, you will work closely with our team of designers and developers to create a user-friendly, responsive, and secure web application that meets the needs of our customers.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1690924425,
        "job_posted_at_datetime_utc": "2023-08-01T21:13:45.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=1MpkfgbWcNMAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Next.js",
            "Tailwind CSS",
            "React"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 35,
        "job_max_salary": 75,
        "job_salary_currency": "USD",
        "job_salary_period": "HOUR",
        "job_highlights": {},
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    }
  ],
  "python": [
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "ZhWWTj6uF5UAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer",
        "job_apply_link": "https://www.upwork.com/freelance-jobs/apply/Python-Developer_~01c06d4d22c42870a8/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6815,
        "job_description": "I'm a software engineer working full-time for a start-up. My brother runs his own law firm. I want to help him automate his business, but I don't have the capacity to do everything.\n\nSo I want to hire someone to help me. I'm looking for a tough Python developer who is growth-oriented, positive and ambitious. If our relationship works out, we will have plenty of work for you in the future.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691482191,
        "job_posted_at_datetime_utc": "2023-08-08T08:09:51.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer&htidocid=ZhWWTj6uF5UAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Python"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 25,
        "job_max_salary": 35,
        "job_salary_currency": "USD",
        "job_salary_period": "HOUR",
        "job_highlights": {},
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "Dice",
        "employer_logo": "https://s24.q4cdn.com/133441296/files/images/brands/dice.png",
        "employer_website": null,
        "employer_company_type": "Information",
        "job_publisher": "LinkedIn",
        "job_id": "Pms361q6ZFoAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Sr. Python Developer - Charlotte, NC (Hybrid) - Locals Only - Contract Role.",
        "job_apply_link": "https://www.linkedin.com/jobs/view/sr-python-developer-charlotte-nc-hybrid-locals-only-contract-role-at-dice-3688301110",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5631,
        "job_description": "Dice is the leading career destination for tech experts at every stage of their careers. Our client, Centraprise Corp, is seeking the following. Apply via Dice today!\n\nPosition: Sr. Python Developer\n\nLocation: Charlotte, NC(Hybrid)\n\nlooking for only locals\n\nHiring Type: Contract\n\nGood to Have:\n• PySpark\n• Airflow\n• Knowledge in Capital Markets domain (Risk, financial pricing, valuations etc.)\n\nJob Summary:\n• Expertise in Core Python programming\n• Working knowledge and experience using threading limitation of Python and multi-pro architecture and event driven programming\n• Experience in scheduling jobs or trigger events programmatically Experience in Data Access and ORM tools like SQL Alchemy\n• Experience working with Pandas, NumPy and Regular Expressions in Python Basic experienc on Web services (Flask, Django), Web Apps(good to have)\n• Hands on experience with JIRA, Agile methodology, source code management-GIT, SVN\n• Understanding of fundamental design principles for building a scalable application\n• Proficiency in implementing automated unit tests. Experience working with Pandas, NumPy and Regular Expressions in Python\n• Basic experience on Web services (Flask, Django), Web Apps(good to have),\n• Hands on experience with JIRA, Agile methodology, source code management -GIT, SVN et\n• Understanding of fundamental design principles for building a scalable application\n• Proficiency in implementing automated unit tests.\"\n\nThanks & Regards,\n\nFarook Shaik\n\nEmail:\n\nSr. Python Developer - Charlotte, NC (Hybrid) - Locals Only - Contract Role.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691489602,
        "job_posted_at_datetime_utc": "2023-08-08T10:13:22.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer&htidocid=Pms361q6ZFoAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-09-07T10:13:22.000Z",
        "job_offer_expiration_timestamp": 1694081602,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Knowledge in Capital Markets domain (Risk, financial pricing, valuations etc.)",
                "Expertise in Core Python programming",
                "Working knowledge and experience using threading limitation of Python and multi-pro architecture and event driven programming",
                "Experience in scheduling jobs or trigger events programmatically Experience in Data Access and ORM tools like SQL Alchemy",
                "Experience working with Pandas, NumPy and Regular Expressions in Python Basic experienc on Web services (Flask, Django), Web Apps(good to have)",
                "Understanding of fundamental design principles for building a scalable application",
                "Proficiency in implementing automated unit tests",
                "Hands on experience with JIRA, Agile methodology, source code management -GIT, SVN et"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_naics_code": "519130",
        "job_naics_name": "Internet Publishing and Broadcasting and Web Search Portals"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "SRI6cqe4atoAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Python Developer (Web Scraping) - Contract to hire",
        "job_apply_link": "https://www.upwork.com/en-gb/freelance-jobs/apply/Python-Developer-Web-Scraping_~01d1cd4fd8e26dc653/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6815,
        "job_description": "As a Python Web Scraping Specialist, you will be responsible for gathering and extracting data from various websites and online sources. Your expertise in Python programming and web scraping tools will play a crucial role in helping us obtain valuable data and insights to support our business objectives.\n\nMandatory Skills: Strong experience in Python, Web Scraping technologies, Handling anti-scraping techniques, and Proxy management/IP rotation.\n\n4+ years of Strong proficiency in Python programming and familiarity with popular Python libraries\n\nShould have knowledge about handling anti-scraping techniques that deter or block automated data extraction.\n\nThese techniques can include CAPTCHAs, IP blocking, rate limiting, and other mechanisms designed to identify and prevent bots.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691391905,
        "job_posted_at_datetime_utc": "2023-08-07T07:05:05.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer&htidocid=SRI6cqe4atoAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Beautiful Soup",
            "Selenium",
            "Data Extraction",
            "Data Integration",
            "Python",
            "Data Scraping",
            "Scrapy",
            "Web Crawling"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 8,
        "job_max_salary": 10,
        "job_salary_currency": "USD",
        "job_salary_period": "HOUR",
        "job_highlights": {
            "Qualifications": [
                "Mandatory Skills: Strong experience in Python, Web Scraping technologies, Handling anti-scraping techniques, and Proxy management/IP rotation",
                "4+ years of Strong proficiency in Python programming and familiarity with popular Python libraries",
                "Should have knowledge about handling anti-scraping techniques that deter or block automated data extraction"
            ],
            "Responsibilities": [
                "As a Python Web Scraping Specialist, you will be responsible for gathering and extracting data from various websites and online sources",
                "Your expertise in Python programming and web scraping tools will play a crucial role in helping us obtain valuable data and insights to support our business objectives"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "World Wide Technology",
        "employer_logo": "https://www.f5.com/content/dam/f5-com/page-assets-en/home-en/services/professional-services/guardian-partners/wwt-logo-color-horizontal-high.eps.png",
        "employer_website": "http://www2.wwt.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "LinkedIn",
        "job_id": "IWxE_0OZA1UAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "100% remote job--Python Developer.",
        "job_apply_link": "https://www.linkedin.com/jobs/view/100%25-remote-job-python-developer-at-world-wide-technology-3681439937",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.562,
        "job_description": "12850\n\nSenior Python Developer\n\nJob Name: Senior Python Developer\n\n6-12 months+\n\nSenior Python Developer for a strategic program to develop the banks next generation of Drift reporting tools.\n\nResource will allow the program to meet delivery targets.\n\nThe objective of the program is to provide transparency into configuration drift for both our Linux and Windows midrange products. Ultimately this effort would drive Operational Excellence.\n\nJob Description:\n\nExperienced senior Python developer who will be responsible for developing and maintaining an enterprise level, multi-tiered Python application. Senior level demonstrated experience designing and developing Python microservices and applications. Demonstrated proficiency with the Red Hat Enterprise Linux operating system, shell scripting, including understanding shared libraries, compilation of applications and dependencies, and building packages. Demonstrated ability to mentor and provide technical best practices to more junior development resources. Large application Engineering and design experience. Demonstrated proficiency communicating application concepts at an appropriate level of detail to both technical peers and management – both written and verbal. Experience developing applications leveraging a relational database – SQL.\n\nSkills:\n• Senior level programming experience in a Python (3.6+) application development environment (building packages, use of virtual environments, cross platform applications)\n• Experience with microservices architecture.\n• Demonstrated proficiency with Git\n• MSSQL Server or equivalent RDBMS experience\n• RHEL Linux – advanced user level including understanding of processes, libraries, compilers, sockets, packaging\n• General knowledge of TCP/IP networking\n• Django REST Framework\n• Large enterprise application development experience\n• Demonstrated application engineering experience\n• Demonstrated problem solving capability\n• Demonstrated application tuning experience\n\nNice to have:\n\nWindows server familiarity, including writing and creating windows services, experience with a variety of web / application server technologies, YAML, Ansible Playbook, Jenkins, Jira, Bitbucket (or GitHub, GitLab), Flask.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691175678,
        "job_posted_at_datetime_utc": "2023-08-04T19:01:18.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer&htidocid=IWxE_0OZA1UAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-09-03T19:01:18.000Z",
        "job_offer_expiration_timestamp": 1693767678,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Experienced senior Python developer who will be responsible for developing and maintaining an enterprise level, multi-tiered Python application",
                "Senior level demonstrated experience designing and developing Python microservices and applications",
                "Demonstrated proficiency with the Red Hat Enterprise Linux operating system, shell scripting, including understanding shared libraries, compilation of applications and dependencies, and building packages",
                "Demonstrated ability to mentor and provide technical best practices to more junior development resources",
                "Large application Engineering and design experience",
                "Demonstrated proficiency communicating application concepts at an appropriate level of detail to both technical peers and management – both written and verbal",
                "Experience developing applications leveraging a relational database – SQL",
                "Senior level programming experience in a Python (3.6+) application development environment (building packages, use of virtual environments, cross platform applications)",
                "Experience with microservices architecture",
                "Demonstrated proficiency with Git",
                "MSSQL Server or equivalent RDBMS experience",
                "RHEL Linux – advanced user level including understanding of processes, libraries, compilers, sockets, packaging",
                "General knowledge of TCP/IP networking",
                "Django REST Framework",
                "Large enterprise application development experience",
                "Demonstrated application engineering experience",
                "Demonstrated problem solving capability",
                "Demonstrated application tuning experience",
                "Windows server familiarity, including writing and creating windows services, experience with a variety of web / application server technologies, YAML, Ansible Playbook, Jenkins, Jira, Bitbucket (or GitHub, GitLab), Flask"
            ],
            "Responsibilities": [
                "Senior Python Developer for a strategic program to develop the banks next generation of Drift reporting tools",
                "Resource will allow the program to meet delivery targets",
                "The objective of the program is to provide transparency into configuration drift for both our Linux and Windows midrange products"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "DtC-2jRpPyEAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Python developer - Contract to Hire",
        "job_apply_link": "https://www.upwork.com/freelance-jobs/apply/Python-developer_~019f710c89245317aa/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6815,
        "job_description": "We are looking for a passionate and motivated Junior Full Stack Developer to join our team and contribute to the development of an exciting mobile application for iOS. This is a great opportunity for a beginner or entry-level developer to gain hands-on experience and enhance their skills in iOS app development.\n\nResponsibilities:\n\nWork closely with our product team to understand the project requirements and contribute to technical discussions.\n\nAssist in building the back-end infrastructure and APIs to support the iOS mobile app.\n\nCollaborate on front-end development tasks, creating user interfaces and implementing design elements.\n\nPerform code testing and debugging under the guidance of senior developers to ensure the app's quality and performance.\n\nLearn and adopt best coding practices and standards within the team.\n\nParticipate in regular team meetings, sharing progress updates and discussing challenges.\n\nRequired Skills:\n\nBasic understanding of programming concepts and some experience with a programming language (Swift and/or Objective-C preferred).\n\nFamiliarity with iOS SDK and Xcode development environment (experience with UIKit or SwiftUI is a plus).\n\nBasic knowledge of front-end technologies like HTML, CSS, and JavaScript.\n\nEagerness to learn and a strong passion for mobile app development.\n\nAbility to work collaboratively in a team environment and adapt to changing project requirements.\n\nDetail-oriented mindset and willingness to follow coding standards.\n\nPreferred Skills:\n\nExperience with version control systems like Git.\n\nKnowledge of RESTful APIs and basic server-side integration concepts.\n\nPrevious exposure to Agile development methodologies.\n\nProject Details:\n\nProject Type: Mobile Application Development (iOS)\n\nProject Duration: Estimated X months, with the possibility of extension based on performance.\n\nTime Zone: [Your Time Zone]\n\nCommunication: We prefer [communication method, e.g., video calls, instant messaging] for regular updates and meetings.\n\nBudget: As a junior developer, your salary will be competitive and commensurate with your experience and skills.\n\nNote: This is an excellent opportunity for a junior developer to gain valuable experience working on a real-world iOS mobile application project. Please include any relevant coursework, personal projects, or code samples in your application.\n\nWe look forward to welcoming a dedicated and enthusiastic Junior Full Stack Developer to our team. Your contributions will play a vital role in the success of our mobile app project. Thank you for considering this opportunity!",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691205765,
        "job_posted_at_datetime_utc": "2023-08-05T03:22:45.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer&htidocid=DtC-2jRpPyEAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": true
        },
        "job_required_skills": [
            "TensorFlow",
            "Python",
            "API",
            "Python Script",
            "langchain",
            "pytorch"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 16,
        "job_max_salary": 55,
        "job_salary_currency": "USD",
        "job_salary_period": "HOUR",
        "job_highlights": {
            "Qualifications": [
                "This is a great opportunity for a beginner or entry-level developer to gain hands-on experience and enhance their skills in iOS app development",
                "Basic knowledge of front-end technologies like HTML, CSS, and JavaScript",
                "Eagerness to learn and a strong passion for mobile app development",
                "Ability to work collaboratively in a team environment and adapt to changing project requirements",
                "Detail-oriented mindset and willingness to follow coding standards",
                "Experience with version control systems like Git",
                "Knowledge of RESTful APIs and basic server-side integration concepts",
                "Previous exposure to Agile development methodologies",
                "Note: This is an excellent opportunity for a junior developer to gain valuable experience working on a real-world iOS mobile application project",
                "Please include any relevant coursework, personal projects, or code samples in your application"
            ],
            "Responsibilities": [
                "Work closely with our product team to understand the project requirements and contribute to technical discussions",
                "Assist in building the back-end infrastructure and APIs to support the iOS mobile app",
                "Collaborate on front-end development tasks, creating user interfaces and implementing design elements",
                "Perform code testing and debugging under the guidance of senior developers to ensure the app's quality and performance",
                "Learn and adopt best coding practices and standards within the team",
                "Participate in regular team meetings, sharing progress updates and discussing challenges"
            ],
            "Benefits": [
                "Budget: As a junior developer, your salary will be competitive and commensurate with your experience and skills"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "SynergisticIT",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "LinkedIn",
        "job_id": "2qE9pv-nCUAAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer (Entry Level)",
        "job_apply_link": "https://www.linkedin.com/jobs/view/python-developer-entry-level-at-synergisticit-3683289791",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5613,
        "job_description": "SYNERGISTICIT is aware that the Job Market is Challenging because of Tech Layoffs due to which The Job market is flooded with hundreds and thousands of laid off Jobseekers who are competing with existing Jobseekers. For entry level Job seekers to get client interviews and jobs they need to differentiate themselves by ensuring they have exceptional skills and technologies to be noticed by clients.\n\nSince 2010 we have helped Jobseekers differentiate themselves by providing the clients with candidates who have the requisite skills and experience to outperform at interviews and clients. Here at SynergisticIT We just don't focus on getting you a Job we make careers.\n\nAll Positions are open for all visas and US citizens\n\nWe at Synergisticit understand the problem of the mismatch between employer's requirements and Employee skills and that's why since 2010 we have helped thousands of candidates get jobs at technology clients like apple, google, Paypal, western union, Client, visa, walmart labs etc to name a few.\n\nWe have an excellent reputation with the clients. Currently, We are looking for entry-level software programmers, Java Full stack developers, Python/Java developers, Data analysts/ Data Scientists, Machine Learning engineers.\n\nWho Should Apply Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates looking to make their careers in IT Industry\n\nWe welcome candidates with all visas and citizens to apply.\n\nWe assist in filing for STEM extension and also for H1b and Green card filing to Candidates\n\nWe also offer Skill enhancement programs for candidates who are either missing skills or are lacking Industry/Client experience with Projects and skills. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. If they are qualified with enough skills and have hands on project work at clients then no need for skill enhancement.\n\nCandidates can benefit from skill enhancement if they fall into the below categories.\n\nCandidates who Lack Experience or are freshers with No actual on Job experience with projects with clients\nHave had a break in careers\nLack Technical Competency or skills being demanded by clients\nDifferent visa candidates (Like OPT/H4EAD/L2EAD )who want to get employed and settle down in the USA\n\nplease check the below links to see success outcomes of our candidates\n\nhttps://www.synergisticit.com/candidate-outcomes/\n\nWatch the below videos of us participating at Industry events with the Top companies in Technology at Oracle Cloud world /Oracle Java one (Las vegas) and at Gartner Data Analytics Summit (Florida)\n\nOracle CloudWorld Event (OCW) Las Vegas 2022 | SynergisticIT - YouTube\nhttps://www.youtube.com/watch?v=OAFOhcGy9Z8\nhttps://www.youtube.com/watch?v=EmO7NrWHkLM\nhttps://www.youtube.com/watch?v=NVBU9RYZ6UI\nhttps://www.youtube.com/watch?v=Yy74yvjatVg\nSynergisticIT at Gartner Data and Analytics Summit 2023 - YouTube\n\nhttps://www.synergisticit.com/java-track/\n\nhttps://www.synergisticit.com/data-science-track/\n\nhttps://www.synergisticit.com/contact-us/\n\nIf you have relevant skills and industry experience, please apply if not then candidates can opt for Skill enhancement.\n\nFor getting help with interviews please visit\n\nhttps://www.synergisticit.com/interview-questions/\n\nREQUIRED SKILLS For Java /Software Programmers\n• Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT\n• Highly motivated, self-learner, and technically inquisitive\n• Experience in programming language Java and understanding of the software development life cycle\n• Project work on the skills\n• Knowledge of Core Java , javascript , C++ or software programming\n• Spring boot, Microservices, Docker, Jenkins and REST API's experience\n• Excellent written and verbal communication skills\n\nFor data Science/Machine learning\nREQUIRED SKILLS\n• Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT\n• Project work on the technologies needed\n• Highly motivated, self-learner, and technically inquisitive\n• Experience in programming language Java and understanding of the software development life cycle\n• Knowledge of Statistics, SAS, Python, Computer Vision, data visualization tools\n• Excellent written and verbal communication skills\nPreferred skills: NLP, Text mining, Tableau, PowerBI, Time series analysis\n\nPlease understand skills and relevant experience on real world projects are required by clients for selection even if its Junior or entry level position the additional skills and Project work with hands on experience building projects at client site are the only way a candidate can be picked by clients. If not having the skills or hands on project work at client site then candidates can opt for skill enhancement to gain the required skills and project work.\n\nNo third party candidates or c2c candidates\n\nplease only apply to the posting\n\nNo phone calls please. Shortlisted candidates would be reached out.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691171174,
        "job_posted_at_datetime_utc": "2023-08-04T17:46:14.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer&htidocid=2qE9pv-nCUAAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-09-03T17:46:13.000Z",
        "job_offer_expiration_timestamp": 1693763173,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": true,
            "degree_preferred": true,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Different visa candidates (Like OPT/H4EAD/L2EAD )who want to get employed and settle down in the USA",
                "REQUIRED SKILLS For Java /Software Programmers",
                "Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT",
                "Highly motivated, self-learner, and technically inquisitive",
                "Experience in programming language Java and understanding of the software development life cycle",
                "Knowledge of Core Java , javascript , C++ or software programming",
                "Spring boot, Microservices, Docker, Jenkins and REST API's experience",
                "Excellent written and verbal communication skills",
                "For data Science/Machine learning",
                "Project work on the technologies needed",
                "Knowledge of Statistics, SAS, Python, Computer Vision, data visualization tools",
                "Please understand skills and relevant experience on real world projects are required by clients for selection even if its Junior or entry level position the additional skills and Project work with hands on experience building projects at client site are the only way a candidate can be picked by clients",
                "If not having the skills or hands on project work at client site then candidates can opt for skill enhancement to gain the required skills and project work"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "Conch Technologies, Inc",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4xJGpCo6ZtT4RFpPxZxa5LKMr0vt1LjnqYuLE&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "LinkedIn",
        "job_id": "Dv5ShVGzXeYAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "100% REMOTE: Python Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/100%25-remote-python-developer-at-conch-technologies-inc-3682900326",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5861,
        "job_description": "HI,\n\nGreetings from Conch Technologies Inc\n\nPosition: Python Developer\n\nLocation: REMOTE\n\nDuration: 12+ Months COntract\n\nPython\n\nBash scripting\n\nData manipulation, test scripting\n\nLinux environments\n\n--\n\nWith Regards,\n\nNagesh G\n\nMobile: 408-381-5645\n\nDesk: 901-313-3066\n\nEmail: nagesh@conchtech.com\n\nWeb: www.conchtech.com",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691108308,
        "job_posted_at_datetime_utc": "2023-08-04T00:18:28.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer&htidocid=Dv5ShVGzXeYAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-09-03T00:18:28.000Z",
        "job_offer_expiration_timestamp": 1693700308,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Bash scripting",
                "Data manipulation, test scripting"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "aAzxvDO0ShkAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Python developer to build a web scraper to scrape homeowner names, city/state, address, & phone #'s",
        "job_apply_link": "https://www.upwork.com/en-gb/freelance-jobs/apply/Python-developer-build-web-scraper-scrape-homeowner-names-city-state-address-phone_~013717d404c005cbf5/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6815,
        "job_description": "Looking for:\n\n-Someone who is seasoned in python & web scraping\n\nI am a solar salesman looking to use this web scraper as a lead generation tool. I get sales by cold calling a specific area/county/zip code.\n\nI am looking to have someone build a bot that has the ability to scrape any zip code or county in the United States for RESIDENTIAL HOMES and their addresses, homeowner names, city/state, and homeowner phone numbers. I would also like to have a GUI of some sort that allows me to type in the zip code and it will start scraping - then, at the end, I'd like to have the option to export them all as a CSV file.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691095825,
        "job_posted_at_datetime_utc": "2023-08-03T20:50:25.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer&htidocid=aAzxvDO0ShkAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Python",
            "Data Scraping",
            "Web Crawling",
            "Data Mining",
            "Scrapy"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Someone who is seasoned in python & web scraping"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113400",
        "job_onet_job_zone": "3",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "oYEHMsi1XNsAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Looking for Python Developer  - Contract to Hire",
        "job_apply_link": "https://www.upwork.com/freelance-jobs/apply/Looking-for-Python-Developer_~01b08f34b5fad63de2/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.7788,
        "job_description": "Are you a skilled and experienced Chrome Extension Developer ready to take on a dynamic role in building and enhancing an innovative email verifier plugin? If so, we've got the perfect opportunity for you!\n\nAbout Us:\n\nWe are a forward-thinking tech startup passionate about creating practical solutions that empower users. Our current focus is on developing an email verifier chrome extension/plugin to ensure accurate and reliable email data.\n\nRole Overview:\n\nWe have successfully laid the foundation with a basic script and chrome extension, and now we're seeking a Senior Chrome Extension Developer to join our team. Your expertise will be essential in taking our project to the next level by implementing advanced features and functionalities.\n\nResponsibilities:\n\nCollaborate with our development team to understand project goals and requirements.\n\nBuild upon the existing structure to develop advanced features for the email verifier chrome extension/plugin.\n\nImplement efficient email verification algorithms to enhance accuracy and speed.\n\nOptimize the extension/plugin for seamless user experience and performance.\n\nStay updated with the latest web technologies and trends to ensure the extension/plugin remains cutting-edge.\n\nParticipate in code reviews and provide constructive feedback to team members.\n\nRequirements:\n\nProven experience in developing Chrome extensions/plugins.\n\nStrong proficiency in JavaScript, HTML, and CSS.\n\nIn-depth knowledge of web development principles and best practices.\n\nFamiliarity with email verification processes and algorithms.\n\nAbility to work collaboratively in a team environment.\n\nExcellent problem-solving skills and a proactive attitude.\n\nStrong communication skills to effectively convey technical concepts.\n\nWhat We Offer:\n\nA unique opportunity to shape the future of our email verifier plugin from the ground up.\n\nA challenging and dynamic work environment where your contributions make a significant impact.\n\nLong-term, full-time engagement with potential for career growth within our expanding company.\n\nCompetitive compensation package and benefits.\n\nFlexible work arrangements and a supportive team culture.\n\nIf you're excited about revolutionizing email verification and have the skills to drive innovation, we want to hear from you!\n\nApplication Process:\n\nTo apply, please send your resume, portfolio (if applicable), and a brief cover letter outlining your relevant experience and why you're interested in this role. In your cover letter, highlight any previous work on Chrome extensions/plugins and email verification.\n\nJoin us in building a cutting-edge email verifier chrome extension/plugin that transforms the way users interact with email data. Apply now and be a part of our journey!",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691054283,
        "job_posted_at_datetime_utc": "2023-08-03T09:18:03.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": [
            "health_insurance"
        ],
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer&htidocid=oYEHMsi1XNsAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Python",
            "API",
            "Python Script",
            "Django",
            "chrome extension"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 20,
        "job_max_salary": 42,
        "job_salary_currency": "USD",
        "job_salary_period": "HOUR",
        "job_highlights": {
            "Qualifications": [
                "Proven experience in developing Chrome extensions/plugins",
                "Strong proficiency in JavaScript, HTML, and CSS",
                "In-depth knowledge of web development principles and best practices",
                "Familiarity with email verification processes and algorithms",
                "Ability to work collaboratively in a team environment",
                "Excellent problem-solving skills and a proactive attitude",
                "Strong communication skills to effectively convey technical concepts"
            ],
            "Responsibilities": [
                "Collaborate with our development team to understand project goals and requirements",
                "Build upon the existing structure to develop advanced features for the email verifier chrome extension/plugin",
                "Implement efficient email verification algorithms to enhance accuracy and speed",
                "Optimize the extension/plugin for seamless user experience and performance",
                "Stay updated with the latest web technologies and trends to ensure the extension/plugin remains cutting-edge",
                "Participate in code reviews and provide constructive feedback to team members"
            ],
            "Benefits": [
                "Long-term, full-time engagement with potential for career growth within our expanding company",
                "Competitive compensation package and benefits",
                "Flexible work arrangements and a supportive team culture"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    },
    {
        "employer_name": "Upwork",
        "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
        "employer_website": "http://www.elance.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "Upwork",
        "job_id": "qnyCL7Gd4lkAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Python Developer For Text & Audio Sync  - Contract to hire",
        "job_apply_link": "https://www.upwork.com/en-gb/freelance-jobs/apply/Python-Developer-For-Text-Audio-Sync_~01c96e09cdda841160/",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.6815,
        "job_description": "I'm looking for a Python developer to create an API. Where text (transcription) and audio will be given. Your job is to generate subtitles using the Aeneas library (Search Aeneas Github) or use any other library.\n\nRemember that we want short subtitles with max 4-5 words per time stamp.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1691310267,
        "job_posted_at_datetime_utc": "2023-08-06T08:24:27.000Z",
        "job_city": null,
        "job_state": null,
        "job_country": "US",
        "job_latitude": 37.09024,
        "job_longitude": -95.71289,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer&htidocid=qnyCL7Gd4lkAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": [
            "Python",
            "C"
        ],
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_naics_code": "541511",
        "job_naics_name": "Custom Computer Programming Services"
    }
  ],
}

